add swift

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -36,6 +36,11 @@ jobs:
         name: Generate gRPC for python
         command: for file in `find ${CIRCLE_PROJECT_REPONAME} -name '*.proto'`; do docker run -v $(pwd):/defs namely/protoc-all -f $file -l python -i ./ ; done
     - run:
+        name: Generate gRPC for swift
+        command: |
+          mkdir -p gen/pb-swift/
+          for file in `find ${CIRCLE_PROJECT_REPONAME} -name '*.proto'`; do docker run --rm -v $(pwd):$(pwd) -w $(pwd) kaito2/swift-protoc:0.1.3 --swift_out=./gen/pb-swift --swiftgrpc_out=./gen/pb-swift -I. $file ; done
+    - run:
         name: Generate gRPC for typescript
         command: docker run -t --rm -v $(pwd):$(pwd) -w $(pwd) kaito22/grpc-gen-typescript:0.1.0 ./protoc.sh
     - persist_to_workspace:
@@ -93,6 +98,25 @@ jobs:
           git -C ./${CIRCLE_PROJECT_REPONAME}python commit -m "gen" || result=$?
           if [ $result -eq 0 ]; then
             git -C ./${CIRCLE_PROJECT_REPONAME}python push origin master 2> /dev/null
+          fi
+    - run:
+        name: git commit swift-src
+        command: |
+          echo "clone swift"
+          clonesuccess=0
+          git clone https://${GH_TOKEN}@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}swift.git || clonesuccess=$?
+          if [ $clonesuccess -eq 128 ]; then
+            echo "swift repository is not found"
+            exit -1
+          fi
+          git -C ./${CIRCLE_PROJECT_REPONAME}swift rm --cached -r .
+          rm -r ${CIRCLE_PROJECT_REPONAME}swift/*
+          cp -r gen/pb-swift/${CIRCLE_PROJECT_REPONAME}/* ${CIRCLE_PROJECT_REPONAME}swift/
+          result=0
+          git -C ./${CIRCLE_PROJECT_REPONAME}swift add .
+          git -C ./${CIRCLE_PROJECT_REPONAME}swift commit -m "gen" || result=$?
+          if [ $result -eq 0 ]; then
+            git -C ./${CIRCLE_PROJECT_REPONAME}swift push origin master 2> /dev/null
           fi
     - run:
         name: git commit typescript-src
